version: '3.1'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=cavid
      - POSTGRES_DB=cavid_db
    # restart: always
  adminer:
    image: adminer
    ports:
      - 8080:8080