# Generated by Django 4.1.7 on 2023-05-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.IntegerField(choices=[(1, 'Teklif'), (2, 'Irad'), (3, 'Sikayet')]),
        ),
    ]
