# Generated by Django 4.1.7 on 2023-05-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_contact_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=50)),
                ('website', models.CharField(max_length=40)),
            ],
        ),
    ]
