# Generated by Django 4.1.7 on 2023-05-04 07:04

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='aboutus',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='category',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 5, 4, 7, 4, 28, 210603, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
    ]
