# Generated by Django 4.1.7 on 2023-05-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_contact_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.IntegerField(choices=[(1, 'Suggestion'), (2, 'Complain'), (3, 'Purpose')]),
        ),
    ]
