# Generated by Django 4.1.7 on 2023-05-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_category_slug_alter_contact_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
